name: Build with Gradle

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Check code formatting
      run: ./gradlew check || true
    
    - name: Build with Gradle
      run: ./gradlew clean build
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: buddi-jar
        path: build/libs/*.jar
        retention-days: 30
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/
        retention-days: 30
