name: Build with Gradle

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: ['11', '17', '21']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: buddi-jar-java${{ matrix.java-version }}
        path: build/libs/*.jar
        retention-days: 30
    
    - name: Run tests
      run: ./gradlew test
      continue-on-error: true
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-java${{ matrix.java-version }}
        path: build/reports/
        retention-days: 30

  build-matrix:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['17']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew (Unix)
      if: runner.os != 'Windows'
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: buddi-jar-${{ matrix.os }}-java${{ matrix.java-version }}
        path: build/libs/*.jar
        retention-days: 30
